FROM node:18-alpine

WORKDIR /app

# Copy package manifests
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the app's source code
COPY . .

# Expose the development port
EXPOSE 3000

# Run the development server
CMD ["npm", "start"]