"""add_pyramid_specific_levels_column

Revision ID: 138cbc15282d
Revises: b443fed0e2db
Create Date: 2025-12-08 13:08:08.223040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '138cbc15282d'
down_revision: Union[str, None] = 'b443fed0e2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dca_configurations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dca_configurations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pair', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entry_order_type', sa.VARCHAR(), server_default=sa.text("'limit'::character varying"), autoincrement=False, nullable=False),
    sa.Column('dca_levels', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('tp_mode', sa.VARCHAR(), server_default=sa.text("'per_leg'::character varying"), autoincrement=False, nullable=False),
    sa.Column('tp_settings', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('max_pyramids', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='dca_configurations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dca_configurations_pkey'),
    sa.UniqueConstraint('user_id', 'pair', 'timeframe', 'exchange', name='uix_user_pair_timeframe_exchange')
    )
    # ### end Alembic commands ###
