"""add_priority_explanation

Revision ID: 972238fb0887
Revises: f3f0425f0bb9
Create Date: 2025-12-06 23:56:40.794256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972238fb0887'
down_revision: Union[str, None] = 'f3f0425f0bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queued_signals', sa.Column('priority_explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queued_signals', 'priority_explanation')
    # ### end Alembic commands ###
