"""initial_schema

Revision ID: bc4a75ae2176
Revises: 
Create Date: 2026-01-08 13:57:09.273231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4a75ae2176'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queued_signals', 'current_loss_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.drop_column('users', 'exchange')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exchange', sa.VARCHAR(), server_default=sa.text("'binance'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('queued_signals', 'current_loss_percent',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
