"""add_webhook_secret_and_api_keys_to_user

Revision ID: d1ca0ad60d16
Revises: b6a0425f0bb7
Create Date: 2025-11-18 13:00:51.314102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ca0ad60d16'
down_revision: Union[str, None] = 'b6a0425f0bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('webhook_secret', sa.String(), nullable=False))
    op.add_column('users', sa.Column('encrypted_api_keys', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_api_keys')
    op.drop_column('users', 'webhook_secret')
    # ### end Alembic commands ###
